# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.1.2-BETA
mod_version_type=beta
mod_id=moanimals
mod_curseforge_id=1336428

maven_group=net.spookly
archives_name=MoAnimals
enabled_platforms=fabric,neoforge


# Minecraft properties
minecraft_version=1.21.5
# Arch Dependencies
architectury_api_version=16.1.4
# Fabric Dependencies
fabric_loader_version=0.18.4
fabric_api_version=0.128.2+1.21.5
# NeoForge Dependencies
neoforge_version=21.5.96
