# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.1.0-BETA
maven_group=net.spookly
archives_name=MoAnimals
enabled_platforms=fabric,neoforge


# Minecraft properties
minecraft_version=1.21.4
# Arch Dependencies
architectury_api_version=14.0.4
# Fabric Dependencies
fabric_loader_version=0.18.4
fabric_api_version=0.119.4+1.21.4
# NeoForge Dependencies
neoforge_version=21.4.156
